export {
  HomePage,
  ProductListCategoryPage,
  ProductListSubCategoryPage,
  AboutWallanticsPage,
  ContactusPage,
  Catalogueg,
  Latestblogseg,
  Blogdetailseg,
  FAQeg,
  Dealershipeg,
  Careerseg,
  CareerDetailsPage,
  Genaralmanagereg,
  Returnpolicyeg,
  Privacypolicyeg,
  Termsconditionseg,
  CartSummaryPage,
  OrderSuccessPage,
  ProductDetailPageUser,
} from "./Home";
export {
  ProfilePage,
  OrderDetailsPage,
  ReturnOrderPage,
  ReviewPage,
  CareerPage,
  AboutUsPage,
  CataloguePage,
  AddNewAddressPage,
} from "./Profile";

export {
  LoginPage,
  ForgotPasswordPage,
  RegisterPage,
  RegisterAgainPass,
} from "./Auth";

export {
  RoomVisualizerPage,
  CustomizedWallpaperPage,
  RotationWallpaperPage,
} from "./Rooms";
export { PaymentPage } from "./ProductDetails";
export {
  ReportPage,
  SettingsPage,
  DashboardPage,
  CustomerPage,
  OrderManagementPage,
  ProductManagementPage,
  AddEditProductPage,
  CouponManagementPage,
  InventoryManagementPage,
  AddEditInstallerPage,
  LeadManagementPage,
  BlogManagementPage,
  AddEditBlogPage,
  EditOrderDetailPage,
  StaffManagementPage,
  ContentManagementPage,
  CareerManagementPage,
  CatalogueManagementPage,
  AddEditCataloguePage,
  CustomerDetailPage,
  OrderDetailPage,
  ProductDetailPage,
  CouponDetailPage,
  StaffDetailPage,
  CareerDetailPage,
  AdminLoginPage,
  NewOrderPage,
  AddNewStaffPage,
  AddNewCouponPage,
} from "./Admin";
